name: Merging Rules
on:
   # Run on pull requests into the #master branch
   pull_request:
      branches: [master]

permissions:
   contents: write
   pull-requests: write

jobs:
   call-e2e-tests:
      name: E2E Tests
      uses: digi-serve/.github/.github/workflows/cypress-e2e-tests.yml@master
   call-dependabot-merge:
      name: Dependabot
      needs: call-e2e-tests
      if: ${{ github.actor == 'dependabot[bot]' }}
      uses: digi-serve/.github/.github/workflows/dependabot-merge.yml@master
      secrets: 
         DEPENDABOT_TOKEN: ${{ secrets.DEPENDABOT_TOKEN }}
