name: PR Merged
# NOTE - this workflow is synced automatically. 
# Edit the template in planning/templates/services/pr-merge-release.yml
on:
  pull_request:
    types: [closed]
    branches: [master]
permissions:
  contents: write
jobs:
  call-get-label:
    name: Label
    uses: digi-serve/.github/.github/workflows/get-pr-release-label.yml@master
  call-e2e-tests:
    name: Test
    needs: [call-get-label]
    # Only run if the PR closed by merging and we have a label
    if: ${{ github.event.pull_request.merged && needs.call-get-label.outputs.valid == 'true' }}
    uses: digi-serve/.github/.github/workflows/cypress-e2e-tests.yml@master
  call-bump-version:
    name: Version
    # Only run if tests pass 
    needs: [ call-get-label, call-e2e-tests ]
    uses: digi-serve/.github/.github/workflows/bump-version.yml@master
    with:
      ref: ${{ github.ref }}
      type: ${{ needs.call-get-label.outputs.label }}
  call-create-release:
    name: Release
    uses: digi-serve/.github/.github/workflows/create-release.yml@master
    needs: [call-bump-version]
    with:
      tag: v${{ needs.call-bump-version.outputs.new_version }}
  call-docker-build:
    uses: digi-serve/.github/.github/workflows/docker-build.yml@master
    needs: [call-bump-version]
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    with:
      tags: master,develop,${{ needs.call-bump-version.outputs.new_version }}
  call-dispatch-runtime-update:
    uses: digi-serve/.github/.github/workflows/dispatch-update.yml@master
    needs: [ call-docker-build, call-bump-version, call-get-label ]
    with:
      type: ${{ needs.call-get-label.outputs.label }}
      version: ${{ needs.call-bump-version.outputs.new_version }}
      app_id: ${{ vars.GS_DEV_APP_ID }}
